In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [6]:
#Deep learning models
from keras.models import Sequential
from keras.layers import Dense,Dropout
from keras.callbacks import EarlyStopping

In [3]:
# Dataset
df=pd.read_csv("/content/housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [7]:
df.shape

(20640, 10)

In [11]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [12]:
 df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [13]:
df.dropna(axis=0,inplace=True)

In [15]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [16]:
df['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     9034
INLAND        6496
NEAR OCEAN    2628
NEAR BAY      2270
ISLAND           5
Name: count, dtype: int64

In [17]:
df['ocean_proximity']=df['ocean_proximity'].map({'<1H OCEAN':0,'INLAND':1,'NEAR OCEAN':2,'NEAR BAY':3,'ISLAND':4})

In [18]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,3
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,3
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,3
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,3
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,3

In [19]:
#Train test split
y=df['median_house_value']
x=df.drop('median_house_value',axis=1)

In [20]:
# convert to numpy array
x = np.array(x)
y = np.array(y)

In [23]:
x

array([[-1.2223e+02,  3.7880e+01,  4.1000e+01, ...,  1.2600e+02,
         8.3252e+00,  3.0000e+00],
       [-1.2222e+02,  3.7860e+01,  2.1000e+01, ...,  1.1380e+03,
         8.3014e+00,  3.0000e+00],
       [-1.2224e+02,  3.7850e+01,  5.2000e+01, ...,  1.7700e+02,
         7.2574e+00,  3.0000e+00],
       ...,
       [-1.2122e+02,  3.9430e+01,  1.7000e+01, ...,  4.3300e+02,
         1.7000e+00,  1.0000e+00],
       [-1.2132e+02,  3.9430e+01,  1.8000e+01, ...,  3.4900e+02,
         1.8672e+00,  1.0000e+00],
       [-1.2124e+02,  3.9370e+01,  1.6000e+01, ...,  5.3000e+02,
         2.3886e+00,  1.0000e+00]])

In [22]:
y

array([452600., 358500., 352100., ...,  92300.,  84700.,  89400.])

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=123)

In [25]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(16346, 9)
(4087, 9)
(16346,)
(4087,)

In [26]:
# Scaling
scaler=MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [27]:
print(x_train)
print(x_test)

[[0.54425229 0.30180659 0.66666667 ... 0.06101974 0.21336947 0.25      ]
 [0.30315361 0.58448459 0.56862745 ... 0.00707237 0.27586516 0.25      ]
 [0.6948118  0.16790648 0.09803922 ... 0.25542763 0.25377581 0.25      ]
 ...
 [0.23601221 0.51328374 0.68627451 ... 0.05411184 0.2810375  0.        ]
 [0.19226857 0.55366631 1.         ... 0.06069079 0.26132053 0.75      ]
 [0.51068159 0.19978746 0.43137255 ... 0.12648026 0.29727866 0.5       ]]
[[0.71922686 0.02231668 0.43137255 ... 0.09769737 0.18199749 0.5       ]
 [0.30620549 0.64718385 0.45098039 ... 0.07976974 0.19436284 0.25      ]
 [0.3387589  0.54091392 0.74509804 ... 0.09917763 0.08313678 0.25      ]
 ...
 [0.15055951 0.62274176 0.76470588 ... 0.06973684 0.23342437 0.        ]
 [0.6103764  0.17534538 1.         ... 0.04276316 0.29645798 0.        ]
 [0.72227874 0.08926674 0.25490196 ... 0.13289474 0.31384395 0.        ]]

In [42]:
#ANN (Building model)

model=Sequential([
    #input layer
    Dense(1000, input_shape=(x_train.shape[1],),activation='relu'),
    Dropout(0.2),
    #Two hidden Layer
    Dense(500,activation='relu'),
    Dropout(0.2),
    Dense(250,activation='relu'),
    Dropout(0.2),
    #output layer
    Dense(1,activation='linear')
])

In [43]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 1000)           │        10,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 1000)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 500)            │       500,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 500)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 250)            │       125,250 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 250)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │           251 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 636,001 (2.43 MB)

 Trainable params: 636,001 (2.43 MB)

 Non-trainable params: 0 (0.00 B)

In [44]:
#Compile
model.compile(
    optimizer='rmsprop',
    loss='mse',
    metrics=['mae'])

In [45]:
#EarlyStopping
es = EarlyStopping(
    monitor='val_loss',
    mode='min',
    patience=50,
    restore_best_weights=True)

In [46]:
# fit the model (training)
history = model.fit(x_train, y_train,
                    validation_data= (x_test, y_test),
                    callbacks=[es],
                    epochs=10,
                    batch_size=50,
                    verbose=1)

Epoch 1/10
327/327 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 24349018112.0000 - mae: 119786.0859 - val_loss: 10588405760.0000 - val_mae: 82258.2734
Epoch 2/10
327/327 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 9453468672.0000 - mae: 76960.6484 - val_loss: 6936412160.0000 - val_mae: 64348.2930
Epoch 3/10
327/327 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 6505917952.0000 - mae: 60765.4766 - val_loss: 5656051712.0000 - val_mae: 54966.8984
Epoch 4/10
327/327 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 6041883136.0000 - mae: 57103.4805 - val_loss: 5466554368.0000 - val_mae: 54867.8047
Epoch 5/10
327/327 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5857077760.0000 - mae: 56003.3125 - val_loss: 5373139456.0000 - val_mae: 55118.4414
Epoch 6/10
327/327 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - loss: 5677415936.0000 - mae: 54798.5742 - val_loss: 5148984320.0000 - val_mae: 52938.4102
Epoch 7/10
327/327 ━━━━━━━━━━━━━━━━━━━━ 10s 16ms/step - loss: 5480918528.0000 - mae: 53726.7695 - val_loss: 5096297984.0000 - val_mae: 53491.8945
Epoch 8/10
327/327 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 5339208192.0000 - mae: 52718.1211 - val_loss: 4814942208.0000 - val_mae: 50140.4219
Epoch 9/10
327/327 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5182780416.0000 - mae: 51877.2656 - val_loss: 4710066176.0000 - val_mae: 48473.8828
Epoch 10/10
327/327 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5057488384.0000 - mae: 50952.3281 - val_loss: 4674099712.0000 - val_mae: 50528.0977

In [47]:
#Metrics and Score

from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,mean_squared_log_error

y_pred = model.predict(x_test)
print("mae :", mean_absolute_error(y_test,y_pred))
print("mse :", mean_squared_error(y_test,y_pred))
print("mae :", mean_squared_log_error(y_test,y_pred))
print("score :", r2_score(y_test,y_pred))

128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
mae : 50528.09887199505
mse : 4674100161.423553
mae : 0.11985080132783013
score : 0.635457900117322

In [48]:
#Predictive System
def pred(longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity):

    features = np.array([longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity])

    features_scaled = scaler.fit_transform([features])

    results = model.predict(features_scaled).reshape(1,-1)

    return results[0]

In [52]:
longitude = -122.2300
latitude  = 37.8800
housing_median_age  = 41.0000
total_rooms        = 880.0000
total_bedrooms   =  129.0000
population     = 322.0000
households          =    126.0000
median_income       =      8.3252
ocean_proximity       =     3.0000

price = pred(longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity)
print(price)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
[277261.88]

In [54]:
model.save("model_ann.h5")

import pickle
pickle.dump(scaler,open('scaler.pkl','wb'))

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.